module.exports =
  'welcome': require '../scenes/welcome/view.coffee'
  'channels': require '../scenes/channels/view.coffee'
  'searching': require '../scenes/searching/view.coffee'
  'connecting': require '../scenes/connecting/view.coffee'
  'profile-and-feed': require '../scenes/profile_and_feed/view.coffee'
  'feed': require '../scenes/feed/view.coffee'
  'explore': require '../scenes/explore/view.coffee'
  'save-to-arena': require '../scenes/save_to_arena/view.coffee'
  'find-friends': require '../scenes/find_friends/view.coffee'
