module.exports =
  templateMap:
    signup: -> require('./templates/signup.jade') arguments...
    login: -> require('./templates/login.jade') arguments...
    register: -> require('./templates/register.jade') arguments...
    forgot: -> require('./templates/forgot.jade') arguments...
    reset: -> require('./templates/reset.jade') arguments...
